language: scala

scala:
- 2.11.11
- 2.12.6

branches:
  only:
    - master

jobs:
  include:
   - stage: release
     scala: 2.11.11
     script:
     - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in credentials.sbt.enc -out credentials.sbt -d
     - openssl aes-256-cbc -K $encrypted_0f90593c4cb0_key -iv $encrypted_0f90593c4cb0_iv -in pgp-key.zip.enc -out pgp-key.zip -d
     - unzip pgp_secrets.zip;
     - sbt ++$TRAVIS_SCALA_VERSION publishSigned sonatypeRelease;

   - stage: release
     scala: 2.12.6
     script:
     - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in credentials.sbt.enc -out credentials.sbt -d
     - openssl aes-256-cbc -K $encrypted_0f90593c4cb0_key -iv $encrypted_0f90593c4cb0_iv -in pgp-key.zip.enc -out pgp-key.zip -d
     - unzip pgp_secrets.zip;
     - sbt ++$TRAVIS_SCALA_VERSION publishSigned sonatypeRelease;

stages:
 - test
 - name: release
   if: type = pull_request
