language: scala

scala:
- 2.11.11
- 2.12.6

branches:
  only:
    - master

jobs:
  include:
   - stage: check_commits
     script:
     - sbt "show suggestedBump";

   - stage: release
     script:
     - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in credentials.sbt.enc -out credentials.sbt -d
     - openssl aes-256-cbc -K $encrypted_0f90593c4cb0_key -iv $encrypted_0f90593c4cb0_iv -in keys.zip.enc -out keys.zip -d
     - unzip keys.zip;
     - git config user.name "Travis CI on behalf of Wellcome"
     - git config user.email "wellcomedigitalplatform@wellcome.ac.uk"
     - git config core.sshCommand "ssh -i ssh-key/id_rsa"
     - git remote set-url origin "git@github.com:wellcometrust/sierra-streams-source.git"
     - sbt ++$TRAVIS_SCALA_VERSION release;

stages:
 - test
 - name: check_commits
   if: type = pull_request
 - name: release
   if: type = push