language: scala

branches:
  only:
    - master

jobs:
  include:
   - stage: test
     scala: 2.11.11
     script:
     - sbt ++$TRAVIS_SCALA_VERSION test

   - stage: test
     scala: 2.12.6
     script:
     - sbt ++$TRAVIS_SCALA_VERSION test

   - stage: release
     scala: 2.11.11
     script:
     - openssl aes-256-cbc -K $encrypted_0f90593c4cb0_key -iv $encrypted_0f90593c4cb0_iv -in pgp-key.zip.enc -out pgp-key.zip -d;
     - unzip -q pgp-key.zip;
     - sbt ++$TRAVIS_SCALA_VERSION publishLocalSigned publishSigned sonatypeRelease;

   - stage: release
     scala: 2.12.6
     script:
     - openssl aes-256-cbc -K $encrypted_0f90593c4cb0_key -iv $encrypted_0f90593c4cb0_iv -in pgp-key.zip.enc -out pgp-key.zip -d;
     - unzip -q pgp-key.zip;
     - sbt ++$TRAVIS_SCALA_VERSION publishLocalSigned publishSigned sonatypeRelease;

stages:
 - test
 - name: release
   if: type = pull_request

env:
  global:
#  Encrypted SONATYPE_USER, SONATYPE_PASSWORD, PGP_PASS
  - secure: bJoASB6VNHk0DMK/AwvQj1Q72/P4jzt9Xu6uWHJrdSJIdkkgxxJ6BlXDHNqcnCn22rpW0/dr34pCtz4oNzZ8HNsGpVra5jc1YuACV3RLNEOmBELFuQI+Dik7jJLsjraQ9BNhAJ6qm3mu4CKV7yGRWRW8jmJ6SbQU4hAlO73M+RgeFJRf35Ly2ZtlSfm69q9bbcudN35sgyrUyYqIc3S7chEWgSrnfluoO+1r5LjjNanwJfIvfyFNNdTIczujJELKw7tNceO9ouaLcxsd6+zJur06U53RrYPvmOLbpv4/F6eDzTX/popeV5grhil2DiuKwLa5kjVH1JwMhbXdLmDUk2SHYf2gbS9E11F4whr29EkvI9Ql0hmqNijqyMO13qr7U1kfrF8aAqhMPquPquPLC3wD74SNj30cpAgO62r4HlbDmYnauJ7srqtsmrUXFllvdp1pJltljWqQcHfI/QWRzYJS3RqcIFUCyIdTMm+hcHYmh9GFsJDn5Hfrf2vg5fQFwA0Ru88Hyg26dlJq/YHSLucG8HPPfzSJ8laVVuN3zRQNNbOkvRqTx4dSbzeDF1ndoSTMXQqzH8BoOGMjWQgVJWmdrshWJGT3o0OSwv3LPN9HSJ6kfbp2Nd4nRRuM9SDMKdxjUDJV/EOTn390caEoimJ794VoppZZZwF3OC+/r34=
  - secure: KoIzPqq9N6z8ecF1FPpMnwCapZmxw84B+S0fFhPG66QDPOq2x/VzGABw42G9W0X5gTiXiPaEnwRSq6xFpo/t/4DSBdixeJzEbgColQyaDkYW70PEz8udVQoxn996e8jMeNR2as4eDCkhKCgk+ZSZ4t66ri4kEfWDNGLQhi5IL0Usow/5XUmZ4CDoYJBWKLczrsfRtEGNeJ9ZSHM46KoK7TrDyDV3cUZwNKYFPvuxp+NkdrpW3iu3tNnl0eAl8mqsM1DkN1+Itgh7volJGtQlKDxnEPSR/dMmEEv6NEpMEPEv50XWAq5K/VAP63i7VZs/meNze4wNp0hleUfSzNQ0QQZho1LAfyzMxHIpqEbHJDAuAte47jE0jMDY+n121I0qtCviNGfOX3HuXxGjEwAPkCHog2QcWhQNPN059w68YC+eZszidlU74359mkk3O3DZMUXYPaGbxWOa5eYh9iBzPNjeOPm6CQhzIINYBt/kWStpEHVFs8ewnBVZ5Si92YDB3FnBPHrp1KnSC0cEgKhGt8n2yMCTfzHP0T2hBzQc+buYtJBZ7udOqOhaQXXUfF3ehM/xAa7LzAC1Y76W73aq4+xw8PRqdzN+VuVvBEwbMYJrnskbAZtkwrfRfAcED40ASOZ3DrzzT7uPDg8h054lGpQLf19uozBHGYpqcASLdWU=
  - secure: fwqyoe/vm9lDRDewnl/s/EQWVmQOY0cegP4laOiphKt6L4ghXY6d76A0X7QvyQrfW33RaXbq2FEpWA+LdDfYJh+51KnSYUZY7+H61Rasqbhodu1v7bdITMEoC+TGGXnzHGvwYHDtQ2ZHirOVEJlSeeJKT6U+1W+Zax3Lybzw8WzHkV037LUyTSZlPo5yP0s7P9oWGGNTKvuy8XJyesOosIlGIV0ecnn/T468zsWZ9Wf698/D+AaHq5aiKZsFBgMGif/LN+Kgxgu4TlHso1sMlMKQJVWExkuIsrtJnYL/68CD3m5LyUTOiV855p1Fgu+VjpNr/uLAY2HJ1ARmvvTIsHdCeqR6m+vaoDEe17ezsfwNKCTn6YCIiAK11CISYdSykTxYkUwPqde++rs0HIVNoroGWq85Lk8wBvqHlLNqCCvX7szUer4vyaTIup8t3jl4lPONLmWQdrjYa8RvFUUwLcC5nj7D3+K7mN5lVuPD/LVe2RzHEJPlh1ySsgAUm93TsHo/heKMUIorjiEaSDpcvXfTzGZjiXwFa6EAekDUOsUrjbh1LnOns1/hb41xILhYbOsLBwokyFumzDaAT4ZCqUXaUUYysWx8CCpZXBL9qzOjaI6fqrkUhE+WEUuHls7nFuotyVwwndGXrzDhZ71KshCc+eKw3KiF3rQKZpxkPp8=
