import sbt.Resolver
import sbtrelease.{Version, versionFormatError}

organization := "uk.ac.wellcome"

name := "sierra-streams-source"

crossScalaVersions := Seq("2.11.11", "2.12.6")


val versions = new {
  val logback = "1.1.8"
  val scalatest = "3.0.1"
  val circeVersion = "0.8.0"
}

val circeDependencies = Seq(
  "io.circe" %% "circe-core" % versions.circeVersion,
  "io.circe" %% "circe-generic"% versions.circeVersion,
  "io.circe" %% "circe-parser"% versions.circeVersion,
  "io.circe" %% "circe-optics" % versions.circeVersion
)

libraryDependencies := Seq(
  "com.github.tomakehurst" % "wiremock" % "2.11.0" % Test,
  "org.scalaj" %% "scalaj-http" % "2.3.0",
  "org.scalatest" %% "scalatest" % versions.scalatest % Test,
  "ch.qos.logback" % "logback-classic" % versions.logback,
  "org.slf4j" % "slf4j-api" % "1.7.25",
  "com.typesafe.akka" %% "akka-stream" % "2.5.6",
  "com.typesafe.akka" %% "akka-stream-testkit" % "2.5.6" % Test
) ++ circeDependencies

resolvers += Resolver.sonatypeRepo("releases")

scalacOptions ++= Seq(
  "-deprecation",
  "-unchecked",
  "-encoding",
  "UTF-8",
  "-Xlint",
  "-Xverify",
  "-feature",
  "-language:postfixOps"
)

// We don't publish SNAPSHOTS but the checkSnapshotDependencies
// step in the releaseProcess checks that the SNAPSHOT version is
// compatible with sonatype and fails without these two lines.
dynverSonatypeSnapshots in ThisBuild := true
version in ThisBuild ~= (_.replace('+', '-'))

publishTo := Some(Opts.resolver.sonatypeStaging)

useGpg := false

parallelExecution in Test := false

pgpPublicRing := baseDirectory.value / "pgp-key" / "pubring.asc"
pgpSecretRing := baseDirectory.value / "pgp-key" / "secring.asc"

releaseVersion := { ver: String =>Version(ver)
  .map(_.withoutQualifier)
  .map(_.bump(suggestedBump.value).string).getOrElse(versionFormatError)
}

// we hide the existing definition for setReleaseVersion to replace it with our own
import sbtrelease.ReleaseStateTransformations.{setReleaseVersion=>_,_}

// This creates a release stage that gets the version from the dynamic one
// based on tags generated by sbt-dynver plugin.
// Inspired from https://blog.byjean.eu/2015/07/10/painless-release-with-sbt.html
lazy val setReleaseVersion: ReleaseStep = { st: State =>
  val extracted = Project.extract(st)
  val currentVersion = extracted.get(version)

  val getReleaseVersionFunction = extracted.runTask(releaseVersion, st)._2
  val selectedVersion = getReleaseVersionFunction(currentVersion)

  st.log.info("Setting version to '%s'." format selectedVersion)
  val useGlobal =Project.extract(st).get(releaseUseGlobalVersion)
  val versionStr = (if (useGlobal) globalVersionString else versionString) format selectedVersion

  reapply(Seq(
    if (useGlobal) version in ThisBuild := selectedVersion
    else version := selectedVersion
  ), st)
}

// In sbt-autoversion plugin, minor is the default bump
// strategy as the minorRegexes matches any string.
// Let's override that so figuring out the next version fails if
// there are no commits that explicitly specify the bumping strategy
minorRegexes := List("""\[?minor\]?.*""").map(_.r)

releaseProcess := Seq(
  checkSnapshotDependencies,
  setReleaseVersion,
  tagRelease,
  releaseStepCommandAndRemaining("+publishSigned"),
  releaseStepCommand("sonatypeReleaseAll"),
  releaseStepCommand(s"git push origin --tags")
)